dist: xenial   # required for Python >= 3.7

language: python
python:
   - "3.7"

install:
  - pip install coveralls
  - pip install coverage
  - pip install -r requirements.txt
  - python setup.py install

script:
  - coverage run --source=benchproc setup.py test

after_success:
  - coveralls
